# Site settings
title: Jekyons
version: "v1"
description: "Stop writing CSS and start building prototypes."
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Tachyons Version
tv: "4.6.1"

# Build settings
markdown: kramdown

# Exclude this stuff
exclude: [node_modules, gulpfile.js]

# Gems
gems:
  - jekyll-seo-tag
